<a href="https://colab.research.google.com/github/AakashYadav6/ML_from_Scratch/blob/master/Aakash_Session_13_Numpy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a= np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
b = np.array([[1,2,3],[3,4,5]])
print(b)

[[1 2 3]
 [3 4 5]]


In [ ]:
c =np.array([[[1,2],[1,5]],[[5,6],[1,2]]])
print(c)

[[[1 2]
  [1 5]]

 [[5 6]
  [1 2]]]


In [ ]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
np.array([1,2,3],dtype=bool)
#non zero value as True


array([ True,  True,  True])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
np.arange(1,11).reshape(2,5)
#product should be equal

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.ones((3,4))
#provide value with tuple


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
 np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random((3,4))

array([[0.6958064 , 0.04735316, 0.64945652, 0.8941813 ],
       [0.98247408, 0.56543542, 0.52421354, 0.5496729 ],
       [0.44751772, 0.85473558, 0.27615959, 0.53833998]])

In [ ]:
np.linspace(-10,10,10)
#start,end,noofitems
#linearly spaced


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a1 = np.arange(10,dtype=np.int32)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a2 = np.arange(12,dtype=float).reshape(3,4)
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [ ]:
a3 = np.arange(8).reshape(2,2,2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
a1.ndim

1

In [ ]:
a2.ndim

2

In [ ]:
a3.ndim

3

In [ ]:
#shape no of rows and columns
a1.shape

(10,)

In [ ]:
a2.shape

(3, 4)

In [ ]:
a3.shape
#first no of 2d arrays then second and third will indicate rows and columns

(2, 2, 2)

In [ ]:
a3.size

8

In [ ]:
a2.size
a2


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a2.itemsize
#individual size

8

In [ ]:
a1.itemsize

4

In [ ]:
a3.itemsize
#32 4 bits and 64 will 8 bits

8

In [ ]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
a3.dtype

dtype('int64')

In [ ]:
a3.astype(np.int32)
#to save space

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [ ]:
a1  =np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
a1 +2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
#relational
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])